version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wmgt-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - API_BASE_URL=${API_BASE_URL}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - HEALTH_CHECK_PORT=${HEALTH_CHECK_PORT:-3000}
    env_file:
      - .env.production
    volumes:
      - ./logs:/app/logs
    ports:
      - "${HEALTH_CHECK_PORT:-3000}:3000"
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  bot-network:
    driver: bridge

volumes:
  bot-logs:
    driver: local