
-- Generated by ORDS REST Data Services 23.2.0.r1770931
-- Schema: WMGT  Date: Sun Aug 24 11:08:17 2025 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'WMGT',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'wmgt',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'leaderboards',
      p_base_path      => '/leaderboards/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'leaderboards',
      p_pattern        => 'course/:code',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'leaderboards',
      p_pattern        => 'course/:code',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 50,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'with w_player as (
    select id player_id
    from wmg_players
   where discord_id = to_number(:discord_id default null on conversion error)
)
select l.pos
     , l.discord_id
     , l.player_name
     , l.score
     , case when l.approved_flag = ''Y'' then ''true'' else ''false'' end isApproved
from wmg_leaderboards_all_v l
where l.course_code = :code
  and (l.approved_flag = ''Y'' 
   or (l.approved_flag is null and l.player_id = (select p.player_id from w_player p))
  )
  and l.pos <= 20
order by l.pos
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'leaderboards',
      p_pattern            => 'course/:code',
      p_method             => 'GET',
      p_name               => 'course_code',
      p_bind_variable_name => 'code',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

    
        
COMMIT;

END;