
-- Generated by ORDS REST Data Services 23.2.0.r1770931
-- Schema: WMGT  Date: Sun Aug 17 11:58:40 2025 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'WMGT',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'wmgt',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'WMGT Tournament',
      p_base_path      => '/tournament/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'preview',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'preview',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select c.id course_id, c.code, c.name, p.hole, p.image_preview, p.mimetype, p.filename
from WMG_COURSE_PREVIEWS_V p
  , wmg_courses c
where p.course_id = c.id
');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'preview/:course/:hole',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'preview/:course/:hole',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select p.mimetype, p.image_preview
from WMG_COURSE_PREVIEWS_V p
  , wmg_courses c
where p.course_id = c.id
  and c.code = :course
  and p.hole = :hole');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'rounds',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'rounds',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
l_clob clob;
l_scope logger_logs.scope%type := ''REST:tournament/rounds'';

begin
logger.log(p_text => ''START'', p_scope => l_scope);
logger.log(p_text => ''week:'' || :week, p_scope => l_scope);
select json_object(
       ''season''  value to_number(substr(s.week,2,2))
     , ''round''   value s.round_num
     , ''easyCourse'' value s.easy_course_code
     , ''hardCourse'' value s.hard_course_code
     , ''scores'' value (
            select json_arrayagg(
                   json_object(
                    ''player''          value r.account
                  , ''id''              value r.player_id
                  , ''easyRoundTotal''  value r.easy_roundTotal
                  , ''easyRoundScore''  value r.easy_roundScore
                  , ''easyScorecard''   value (
                      select json_arrayagg(u.par order by u.h)
                       from wmg_rounds_unpivot_mv u
                      where u.player_id = r.player_id
                        and u.course_id =' || ' s.easy_course_id
                        and u.week = r.week
                     )
                  , ''hardScorecard''   value (
                      select json_arrayagg(u.par order by u.h)
                       from wmg_rounds_unpivot_mv u
                      where u.player_id = r.player_id
                        and u.course_id = s.hard_course_id
                        and u.week = r.week
                     ) RETURNING CLOB 
               ) RETURNING CLOB
             ) 
             from (
             select week
                  , account
                  , player_id
                  , easy_roundScore
                  , hard_roundScore
                  , easy_roundTotal
                  , hard_roundTotal
             from (

             select r.week
                  , r.account
                  , r.player_id
                  , r.round_strokes
                  , r.under_par
                  , tc.course_no
               from wmg_' || 'rounds_v r
                  , wmg_tournament_courses tc
              where r.tournament_session_id = tc.tournament_session_id
                and r.course_id = tc.course_id
                and r.week = :week -- s.week
                -- and r.account in (''INDY'', ''his.Dudeness'') -- , ''Blutes87'', ''Browner'', ''B8Y'')
              )
              pivot (
                  sum(under_par) roundScore, sum(round_strokes) roundTotal for course_no in (
                    1 EASY, 2 HARD
                   )
                )
             
             ) r
       ) RETURNING CLOB
    ) d
  into l_clob
  from wmg_tournament_sessions_v s
 where s.week = :week;

apex_util.prn (
        p_clob   => l_clob
      , p_escape => false );

end;
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'WMGT Tournament',
      p_pattern            => 'rounds',
      p_method             => 'GET',
      p_name               => 'week',
      p_bind_variable_name => 'week',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'season',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'season',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'declare
l_clob clob;
begin
select json_arrayagg(
      json_object(
       ''season''  value to_number(substr(s.week,2,2))
     , ''round''   value s.round_num
     , ''easyCourse'' value s.easy_course_code
     , ''hardCourse'' value s.hard_course_code
     , ''scores'' value (
            select json_arrayagg(
                   json_object(
                    ''player''          value r.account
                  , ''id''              value r.player_id
                  , ''easyRoundTotal''  value r.easy_roundTotal
                  , ''easyRoundScore''  value r.easy_roundScore
                  , ''easyScorecard''   value (
                      select json_arrayagg(u.par order by u.h)
                       from wmg_rounds_unpivot_mv u
                      where u.player_id = r.player_id
                        and u.course_id = s.easy_course_id
                        and u.week = r.week
                     )
                  , ''hardScorecard''   value (
                   ' || '   select json_arrayagg(u.par order by u.h)
                       from wmg_rounds_unpivot_mv u
                      where u.player_id = r.player_id
                        and u.course_id = s.hard_course_id
                        and u.week = r.week
                     ) RETURNING CLOB 
               ) RETURNING CLOB
             ) 
             from (
             select week
                  , account
                  , player_id
                  , easy_roundScore
                  , hard_roundScore
                  , easy_roundTotal
                  , hard_roundTotal
             from (

             select r.week
                  , r.account
                  , r.player_id
                  , r.round_strokes
                  , r.under_par
                  , tc.course_no
               from wmg_rounds_v r
                   , wmg_tournament_courses tc
              where r.tournament_session_id = tc.tournament_session_id
                and r.' || 'course_id = tc.course_id
                and r.week like substr(:season,1,3) || ''%''
                -- and r.account in (''INDY'', ''his.Dudeness'') -- , ''Blutes87'', ''Browner'', ''B8Y'')
              )
              pivot (
                  sum(under_par) roundScore, sum(round_strokes) roundTotal for course_no in (
                    1 EASY, 2 HARD
                   )
                )

             ) r
       ) RETURNING CLOB
  ) RETURNING CLOB
    ) d
  into l_clob
  from wmg_tournament_sessions_v s
 where s.week like substr(:season,1,3) || ''%'';

apex_util.prn (
        p_clob   => l_clob
      , p_escape => false );
end;
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'WMGT Tournament',
      p_pattern            => 'season',
      p_method             => 'GET',
      p_name               => 'season',
      p_bind_variable_name => 'season',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'S01,S02, etc...');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'signups',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'signups',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'with curr as (
select s.week, s.id tournament_session_id
     , s.rooms_open_flag
from wmg_tournament_sessions s
where s.tournament_id in (
    select id
      from wmg_tournaments
     where current_flag = ''Y''
)
and s.session_date+1 >= trunc(current_timestamp)
and s.completed_ind = ''N''
order by s.session_date desc
fetch first 1 rows only
)
, last_player as (
    select player_name
    from (
      select tp.player_name, row_number() over (order by tp.tournament_player_created desc) rn
      from wmg_tournament_player_v tp
        , curr
    where tp.tournament_session_id = curr.tournament_session_id
      and tp.active_ind = ''Y''
    )
    where rn = 1
)
select ''application/json'' content_type
    ,  json_object(
     ''week'' value s.week
   , ''rooms_open'' value s.rooms_open_flag
   , ''players'' value s.players
   , ''newPlayers'' value s.new_players
   , ''latestPlayer'' value last_player.player_name
      , ''results'' value (
       select  json_arrayagg(
  ' || '        json_object(''player'' value p.player_result)
        ) 
        from (
          select p.*
            from (
            select p.pos, p.total_score || '' '' || pp.player_name player_result
                , row_number() over (order by p.total_score, pp.player_name) rn
            from wmg_tournament_session_points_v p
               , curr
               , wmg_players_v pp
            where p.tournament_session_id = curr.tournament_session_id
              and p.player_id = pp.id
            ) p
            where p.pos <= 3
            order by p.rn
          ) p
      )  -- results content
 ) content
from (
    select curr.week
          , curr.rooms_open_flag
          , count(*) players
          , sum(decode(tp.rank_code, ''NEW'', 1, 0)) new_players
    from wmg_tournament_player_v tp
        , curr
    where tp.tournament_session_id = curr.tournament_session_id
      and tp.active_ind = ''Y''
    group by curr.week, curr.rooms_open_flag
) s
, last_' || 'player
');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'courses',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'courses',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 100,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'with w_best_round as (
  select course_id, h, score
  from (
    select course_id, h, score, row_number()  over (partition by course_id, h order by people desc) rn
    from (
        select u.course_id, u.h, u.score, count(*) people
          from  wmg_rounds_unpivot_mv u
         where u.player_id != 0  -- remove the curated system score
         group by u.course_id, u.h, u.score
    )
  )
 where rn = 1
)
, w_realistic as (
select *
from w_best_round
 pivot (
   max(score) for h in (
    1 as h1,
    2 as h2,
    3 as h3,
    4 as h4,
    5 as h5,
    6 as h6,
    7 as h7,
    8 as h8,
    9 as h9,
    10 as h10,
    11 as h11,
    12 as h12,
    13 as h13,
    14 as h14,
    15 as h15,
    16 as h16,
    17 as h17,
    18 as h18
   )
 )
)
select c.course_id, c.code, c.name, c.course_group, c.course_mode, c.release_order, c.release_date, c.course_par
     , r.h1 realistic_h1
     , r.h2 realistic_h2
     , r.h3 realistic_h3
     , r.h4 reali' || 'stic_h4
     , r.h5 realistic_h5
     , r.h6 realistic_h6
     , r.h7 realistic_h7
     , r.h8 realistic_h8
     , r.h9 realistic_h9
     , r.h10 realistic_h10
     , r.h11 realistic_h11
     , r.h12 realistic_h12
     , r.h13 realistic_h13
     , r.h14 realistic_h14
     , r.h15 realistic_h15
     , r.h16 realistic_h16
     , r.h17 realistic_h17
     , r.h18 realistic_h18
    , r.h1+ r.h2+ r.h3+ r.h4+ r.h5+ r.h6+ r.h7+ r.h8+ r.h9+ r.h10+ r.h11+ r.h12+ r.h13+ r.h14+ r.h15+ r.h16+ r.h17+ r.h18 - c.course_par course_realistic_score
    , c.best_under utopian
from wmg_courses_v c
   , w_realistic r
 where c.course_id = r.course_id (+)
 order by c.release_order, c.course_mode
');


  -- Template: /current_tournament
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'current_tournament',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Get current active tournament with sessions and courses');

  -- Handler: GET /api/tournaments/current
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'current_tournament',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => 'Returns current active tournament with available sessions and courses',
      p_source         => 
'declare
  l_clob clob;
  l_scope logger_logs.scope%type := ''REST:current_tournament'';
begin
  logger.log(p_text => ''START'', p_scope => l_scope);

  select json_object(
    ''tournament'' value json_object(
      ''id'' value t.tournament_id,
      ''name'' value t.name,
      ''code'' value t.code
    )
    ,''sessions'' value json_object(
          ''id'' value t.tournament_session_id,
          ''week'' value t.week,
          ''session_date'' value to_char(t.session_date, ''YYYY-MM-DD"T"HH24:MI:SS"Z"''),
          ''open_registration_on'' value to_char(t.open_registration_on, ''YYYY-MM-DD"T"HH24:MI:SS"Z"''),
          ''close_registration_on'' value to_char(t.close_registration_on, ''YYYY-MM-DD"T"HH24:MI:SS"Z"''),
          ''registration_open'' value case 
            when current_timestamp between t.open_registration_on and t.close_registration_on 
            then ''true'' else ''false'' end
            ,''available_time_slots'' value (
            select json_arrayagg(
              j' || 'son_object(
                ''time_slot'' value ts.time_slot,
                ''day_offset'' value ts.day_offset,
                ''display'' value ts.prepared_time_slot
              ) order by ts.seq
            )
            from wmg_time_slots_all_v ts
          )
          ,''courses'' value (
            select json_arrayagg(
              json_object(
                ''course_no'' value case when tc.course_no = 1 then 1 else 2 end,
                ''course_name'' value c.name,
                ''course_code'' value c.code,
                ''difficulty'' value case when tc.course_no = 1 then ''Easy'' else ''Hard'' end
              )
            )
            from wmg_tournament_courses tc
            join wmg_courses c on tc.course_id = c.id
            where tc.tournament_session_id = t.tournament_session_id
          )
        -- returning clob
      )
    )
    -- returning clob
  into l_clob
  from (
    select t.id tournament_id, t.name, t.code
    , s.tournament_ses' || 'sion_id
    , s.week
    , s.session_date
    , s.open_registration_on
    , s.close_registration_on
    from wmg_tournaments t
        , wmg_tournament_sessions_v s
    where s.tournament_id = t.id
      and t.current_flag = ''Y''
      and t.active_ind = ''Y''
        and s.session_date + 1 >= trunc(current_timestamp)
        and s.completed_ind = ''N''
    fetch first 1 rows only
  ) t;

  if l_clob is null then
    l_clob := ''{}'';
    /*
    json_object(
      ''tournament'' value null,
      ''sessions'' value json_array()
    );
    */
  end if;

 sys.owa_util.mime_header(''application/json'', true);
  apex_util.prn(
    p_clob   => l_clob,
    p_escape => false
  );

  logger.log(p_text => ''END'', p_scope => l_scope);
exception
  when others then
    logger.log_error(p_text => sqlerrm, p_scope => l_scope);
    raise;
end;');


  -- Template: /players/registrations/{discord_id}
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'players/registrations/:discord_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Get player registrations by Discord ID');

  -- Handler: GET /api/players/registrations/{discord_id}
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'WMGT Tournament',
      p_pattern        => 'players/registrations/:discord_id',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 0,
      p_mimes_allowed  => NULL,
      p_comments       => 'Returns all active registrations for a player by Discord ID',
      p_source         => 
'declare
  l_clob clob;
  l_discord_id varchar2(50);
  l_player_id number;
  l_player_name varchar2(100);
  l_scope logger_logs.scope%type := ''REST:/players/registrations'';
begin
  logger.log(p_text => ''START'', p_scope => l_scope);
  
  l_discord_id := :discord_id;
  logger.log(p_text => ''discord_id: '' || l_discord_id, p_scope => l_scope);
  
  -- Get player info
  select id, player_name
  into l_player_id, l_player_name
  from wmg_players_v
  where discord_id = to_number(l_discord_id default null on conversion error);
  
  -- Build response
  select json_object(
    ''player'' value json_object(
      ''id'' value l_player_id,
      ''name'' value l_player_name,
      ''discord_id'' value l_discord_id
    ),
    ''registrations'' value (
      select json_arrayagg(
        json_object(
          ''session_id'' value tp.tournament_session_id,
          ''week'' value ts.week,
          ''time_slot'' value tp.time_slot,
          ''session_date'' value to_char(ts.session_date, ''YYYY-MM-DD"T"HH24:MI:SS"Z"''),
          ''room_no'' value tp.room_no
        ) returning clob
      )
      from wmg_tournament_players tp
      join wmg_tournament_sessions ts on tp.tournament_session_id = ts.id
      where tp.player_id = l_player_id
        and tp.active_ind = ''Y''
        and ts.session_date + 1 >= trunc(current_timestamp)
      order by ts.session_date
    ) returning clob
  ) into l_clob;

  if l_clob is null then
    l_clob := json_object(
      ''player'' value json_object(
        ''id'' value l_player_id,
        ''name'' value l_player_name,
        ''discord_id'' value l_discord_id
      ),
      ''registrations'' value json_array()
    );
  end if;

  apex_util.prn(
    p_clob   => l_clob,
    p_escape => false
  );

  logger.log(p_text => ''END'', p_scope => l_scope);
exception
  when no_data_found then
    l_clob := json_object(
      ''success'' value false,
      ''error_code'' value ''PLAYER_NOT_FOUND'',
      ''message'' value ''Discord user not linked to WMGT player account''
    );
    apex_util.prn(p_clob => l_clob, p_escape => false);
    logger.log_error(p_text => ''Player not found: '' || l_discord_id, p_scope => l_scope);
  when others then
    logger.log_error(p_text => sqlerrm, p_scope => l_scope);
    raise;
end;');

  -- Define parameter for discord_id
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'WMGT Tournament',
      p_pattern            => 'players/registrations/:discord_id',
      p_method             => 'GET',
      p_name               => 'discord_id',
      p_bind_variable_name => 'discord_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'Discord user ID');

COMMIT;

END;
/