create table wmg_courses (
    id                             number generated by default on null as identity 
                                   constraint courses_id_pk primary key,
    course_group                   varchar2(2 char) generated always as (substr(code, 1, 2))
    code                           varchar2(5 char)
                                   constraint courses_code_unq unique,
    name                           varchar2(255 char) not null,
    course_mode                    varchar2(1 char) constraint courses_course_mode_ck
                                   check (course_mode in ('E','H')),
    release_order                  number not null,
    release_date                   date not null,
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

create or replace trigger wmg_courses_bu
    before update 
    on wmg_courses
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_courses_bu;
/