-- drop table wmg_teams purge;
create table wmg_teams (
    id                             number generated by default on null as identity 
                                   constraint wmg_teams_id_pk primary key
  , tournament_id                  number not null
                                   constraint wmg_teams_tournament_fk
                                   references wmg_tournaments(id)
  , team_name                      varchar2(40) not null
  , team_passcode                  varchar2(60) not null
  , team_logo                      blob
  , mimetype                       varchar2(255)
  , filename                       varchar2(400)
  , image_last_update              timestamp (6) with local time zone
  , verified_by                    varchar2(60)
  , verified_on                    timestamp with local time zone
  , verified_note                  varchar2(200)
  , team_complete_ind              varchar2(1) default 'N'constraint wmg_teams_ck_complete check (team_complete_ind in ('Y', 'N')) not null
  , team_completed_on              timestamp with local time zone
  , active_ind                     varchar2(1) default 'Y'constraint wmg_teams_ck_active check (active_ind in ('Y', 'N')) not null
  , created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
  , created_on                     timestamp with local time zone default on null current_timestamp not null
  , updated_by                     varchar2(60 char)
  , updated_on                     timestamp with local time zone
)
;

-- table index
create unique index wmg_teams_u1 on wmg_teams (tournament_id, lower(team_name));

-- comments
comment on table wmg_teams is 'Teams for tournament';
comment on column wmg_teams.team_passcode is 'passcode shared between teams so they can join';

create or replace trigger wmg_teams_bu
    before update 
    on wmg_teams
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_teams_bu;
/
