create table wmg_parameters (
    id            number        generated by default on null as identity (start with 1) primary key not null
  , category      varchar2(100) not null
  , name_key      varchar2(200) not null
  , value         varchar2(4000)
  , description   varchar2(4000)
  , created_on                     timestamp with local time zone default on null current_timestamp not null
  , created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
  , updated_on                     timestamp with local time zone
  , updated_by                     varchar2(60 char)
  , constraint wmg_parameters_u unique (name_key)
)
enable primary key using index
/

comment on table wmg_parameters is 'System parameters';

comment on column wmg_parameters.category is 'Informational field to group parameters by functional area. New categories are added by a developer.';
comment on column wmg_parameters.name_key is 'Unique name of a parameter';
comment on column wmg_parameters.value is 'Value associated with a parameter';
comment on column wmg_parameters.created_by is 'User that created this record';
comment on column wmg_parameters.created_on is 'Date the record was first created';
comment on column wmg_parameters.updated_by is 'User that last modified this record';
comment on column wmg_parameters.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger wmg_parameters_bu
--------------------------------------------------------
create or replace trigger wmg_parameters_bu
before update
on wmg_parameters
referencing old as old new as new
for each row
begin
  if updating then

    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(
                           sys_context('APEX$SESSION','app_user')
                         , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                         , sys_context('userenv','session_user')
                       );
  end if;
end;
/
