-- drop table wmg_tournament_rooms purge;
create table wmg_tournament_rooms (
    id                             number generated by default on null as identity 
                                   constraint wmg_tournament_room_id_pk primary key,
    tournament_session_id          number not null
                                   constraint wmg_tournamen_tournament_fk16
                                   references wmg_tournament_sessions(id),
    time_slot                      varchar2(5 char) constraint wmg_tournament_room_time_slo_ck
                                   check (time_slot in ('00:00', '02:00','04:00','08:00','12:00','16:00','18:00','20:00', '22:00')) not null,
    room_no                        number not null,
    verified_score_flag            varchar2(1),
    verified_by                    varchar2(60),
    verified_on                    timestamp with local time zone,
    verified_note                  varchar2(200),
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

-- table index
create unique index wmg_tournament_room_u1 on wmg_tournament_rooms (tournament_session_id,time_slot,room_no);

-- comments
comment on table wmg_tournament_rooms is 'Rooms defined for a tournament session';
comment on column wmg_tournament_rooms.verified_score_flag is 'Indicates the room has been verified';

create or replace trigger wmg_tournament_rooms_bu
    before update 
    on wmg_tournament_rooms
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_tournament_rooms_bu;
/
