create table wmg_tournament_sessions (
    id                             number generated by default on null as identity 
                                   constraint wmg_tournament_ses_id_pk primary key,
    tournament_id                  number
                                   constraint wmg_tournament_tournament_fk
                                   references wmg_tournaments not null,
    round_num                      integer not null,
    session_date                   date,
    week                           varchar2(10 char) constraint wmg_tournament_sessions_uk1 unique not null,
    open_registration_on           timestamp with time zone,
    close_registration_on          timestamp with time zone,
    registration_closed_flag       varchar2(1),
    rooms_open_flag                varchar2(1),
    rooms_defined_flag             varchar2(1),
    rooms_defined_by               varchar2(60 char),
    rooms_defined_on               timestamp with time zone,
    completed_ind                  varchar2(1 char) constraint wmg_tournament_completed_i_ck
                                   check (completed_ind in ('Y','N')) not null,
    completed_on                   timestamp with local time zone,
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

-- table index
create index wmg_tournament_ses_i1 on wmg_tournament_sessions (tournament_id);
-- alter table wmg_tournament_sessions modify week unique;
-- comments
comment on column wmg_tournament_sessions.week is 'If prefixes are specified this value gets derived';
comment on column wmg_tournament_sessions.rooms_open_flag is 'Allows the room definitions to be visible to all players';
comment on column wmg_tournament_sessions.rooms_defined_flag is 'Indicates the rooms have been defined and set';

create or replace trigger wmg_tournament_sessions_bu
    before update 
    on wmg_tournament_sessions
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_tournament_sessions_bu;
/
