-- drop table wmg_player_moderation purge;
create table wmg_player_moderation (
    id                             number generated by default on null as identity 
                                   constraint wmg_player_moderation_id_pk primary key
  , player_id                      number not null constraint wmg_player_moderation_player_i_fk references wmg_players(id)
  , notes                          varchar2(4000)
  , player_message                 varchar2(4000)
  , banned_flag                    varchar2(1)
  , timeout_flag                   varchar2(1)
  , timeout_tournament_id          number constraint wmg_player_moderation_tournament_fk references wmg_tournaments(id)
  , timeout_end_date               timestamp with local time zone
  , active_ind                     varchar2(1) constraint wmg_player_moderation_ck_active check (active_ind in ('Y', 'N')) not null
  , created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
  , created_on                     timestamp with local time zone default on null current_timestamp not null
  , updated_by                     varchar2(60 char)
  , updated_on                     timestamp with local time zone
)
;

-- table index
create unique index wmg_player_moderation_pla_u1 on wmg_player_moderation (player_id); -- one mod per player

-- comments
comment on table wmg_player_moderation is 'Players with a moderation';
comment on column wmg_player_moderation.notes is 'Private notes regarding the player';
comment on column wmg_player_moderation.player_message is 'Message given to the player explaining the moderation';
comment on column wmg_player_moderation.timeout_tournament_id is 'If set the player has a timeout for the complete season';
comment on column wmg_player_moderation.timeout_tournament_id is 'If set the player has a timeout that ends on the specified date';

create or replace trigger wmg_player_moderation_bu
    before update 
    on wmg_player_moderation
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_tournament_players_bu;
/
