-- create tables
create table wmg_players (
    id                             number generated by default on null as identity 
                                   constraint players_id_pk primary key,
    account                        varchar2(32 char),
    name                           varchar2(60 char),
    discord_id                     number,
    discord_avatar                 varchar2(62),
    discord_discriminator          varchar2(10),
    account_login                  varchar2(100),
    prefered_tz                    varchar2(20),
    country_code                   varchar2(5),
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

create unique index wmg_players_u01 on wmg_players (lower(account));
create unique index wmg_players_u02 on wmg_players (lower(name));
create unique index wmg_players_u03 on wmg_players (discord_id);

-- comments
comment on column wmg_players.account is 'discord name';
comment on column wmg_players.discord_avatar is 'Get an avatar via https://cdn.discordapp.com/avatars/{G_DISCORD_ID}/{G_DISCORD_AVATAR}.png';
