create table wmg_tournament_courses (
    id                             number generated by default on null as identity 
                                   constraint wmg_tournament_cou_id_pk primary key,
    tournament_session_id          number
                                   constraint wmg_tournamen_tournament_se_fk
                                   references wmg_tournament_sessions(id),
    course_no                      number not null,
    course_id                      number
                                   constraint wmg_tournament_cou_course_i_fk
                                   references wmg_courses(id),
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

-- table index
create index wmg_tournament_cou_i1 on wmg_tournament_courses (course_id);
create index wmg_tournament_cou_i2 on wmg_tournament_courses (tournament_session_id);
