create table wmg_tournaments (
    id                             number generated by default on null as identity 
                                   constraint wmg_tournaments_id_pk primary key,
    code                           varchar2(20 char)
                                   constraint wmg_tournaments_code_unq unique not null,
    name                           varchar2(60 char)
                                   constraint wmg_tournaments_name_unq unique not null,
    prefix_tournament              varchar2(10 char),
    prefix_session                 varchar2(10 char),
    current_flag                   varchar2(1 char),
    active_ind                     varchar2(1 char) constraint wmg_tournaments_active_ind_ck
                                   check (active_ind in ('Y','N')) not null,
    url                            varchar2(4000 char),
    prefix_room_name               varchar2(10 char) default 'WMGT',
    notes                          varchar2(4000 char),
    start_date                     date,
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

-- comments
comment on column wmg_tournaments.prefix_tournament is 'The tournament prefix gets concatenated with the session prefix and round_num to form the "WEEK"';
comment on column wmg_tournaments.start_date is 'Date the tournament begins (in UTC time so no TZ)';

-- triggers
create or replace trigger wmg_tournaments_bu
    before update 
    on wmg_tournaments
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_tournaments_bu;
/
