create table wmg_course_previews (
    id                             number generated by default on null as identity 
                                   constraint wmg_course_previews_id_pk primary key
  , course_id                      number
                                   constraint wmg_course_previews_course_id_fk
                                   references wmg_courses on delete cascade
  , hole                           integer not null
  , same_as_id         number
  , image_preview      blob
  , mimetype           varchar2(255)
  , filename           varchar2(400)
  , image_last_update  timestamp (6) with local time zone
  , created_on         timestamp with local time zone default on null current_timestamp not null
  , created_by         varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
  , updated_on         timestamp with local time zone
  , updated_by         varchar2(60 char)
)
;

-- table index
create unique index wmg_course_previews_u01 on wmg_course_previews (course_id, hole);

-- comments
comment on table wmg_course_previews is 'Preview images per hole';
comment on column wmg_course_previews.same_as_id is 'ID of a whole image that looks the same';


-- triggers
create or replace trigger wmg_course_previews_bu
    before update 
    on wmg_course_previews
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_course_previews_bu;
/
