-- drop table wmg_tournament_room_template purge;
create table wmg_tournament_room_template (
    id                             number generated by default on null as identity 
                                   constraint wmg_tournament_room_tpl_pk primary key,
    tournament_id                  number not null
                                   constraint wmg_tournamet_room_tpl_fk
                                   references wmg_tournaments(id),
    room_no                        number not null,
    extra_rooms                    number,
    day_offset                     number not null,
    time_slot                      varchar2(5 char) not null,
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

-- table index
create unique index wmg_tournament_room_template_u1 on wmg_tournament_room_template (tournament_id,room_no);
create unique index wmg_tournament_room_template_u2 on wmg_tournament_room_template (tournament_id,day_offset,time_slot);

-- comments
comment on table wmg_tournament_room_template is 'List of Possible Rooms for a tournament';
comment on column wmg_tournament_room_template.room_no is 'Actual room number, must be unique 1..N and it is tied to a time (day_offset and time_slot)';
comment on column wmg_tournament_room_template.extra_rooms is 'For a given room number, how many rooms do we need A,B,C...';
comment on column wmg_tournament_room_template.day_offset is 'Days from the start of the tournament';
comment on column wmg_tournament_room_template.time_slot is 'Timeslot for a given day_offset';

create or replace trigger wmg_tournament_room_template_bu
    before update 
    on wmg_tournament_room_template
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_tournament_room_template_bu;
/
