-- drop table wmg_team_players purge;
create table wmg_team_players (
    id                             number generated by default on null as identity 
                                   constraint wmg_teams_players_id_pk primary key
  , tournament_id                  number not null
                                   constraint wmg_teams_pla_tour_fk
                                   references wmg_tournaments(id)
  , team_id                        number not null
                                   constraint wmg_teams_fk
                                   references wmg_teams(id) cascade delete
  , player_id                      number not null
                                   constraint wmg_teams_player_fk
                                   references wmg_players(id)
  , team_captain_flag              varchar2(1)
  , created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
  , created_on                     timestamp with local time zone default on null current_timestamp not null
  , updated_by                     varchar2(60 char)
  , updated_on                     timestamp with local time zone
)
;

-- table index
create unique index wmg_team_player_u1 on wmg_team_players (team_id, player_id);
create unique index wmg_team_player_u2 on wmg_team_players (tournament_id, player_id);

-- comments
comment on table wmg_team_players is 'Players signed up for a Team';

create or replace trigger wmg_team_players_bu
    before update 
    on wmg_team_players
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_team_players_bu;
/
