create table wmg_notes (
    id                             number generated by default on null as identity 
                                   constraint wmg_notes_id_pk primary key,
    note_type                      varchar2(20 char) not null,
    display_seq                    number not null,
    notes                          varchar2(4000 char),
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

create or replace trigger wmg_notes_bu
    before update 
    on wmg_notes
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_notes_bu;
/