-- drop table wmg_matches purge;
create table wmg_matches (
    id                   number generated by default on null as identity 
                         constraint wmg_matches_pk primary key
  , tournament_id        number not null
                         constraint wmg_matches_tournament_fk
                         references wmg_tournaments(id)
  , round_number         number not null -- 1 for first round, 2 for second, etc.
  , match_number         number not null -- Unique within a round
  , team_1_id           number not null
                         constraint wmg_matches_team1_fk
                         references wmg_teams(id)
  , team_2_id           number not null
                         constraint wmg_matches_team2_fk
                         references wmg_teams(id)
  , winning_team_id     number 
                         constraint wmg_matches_winner_fk
                         references wmg_teams(id)
  , match_status        varchar2(10) default 'PENDING' 
                         constraint wmg_matches_status_ck check (match_status in ('PENDING', 'SCHEDULED', 'CANCELED', 'COMPLETED'))
  , created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
  , created_on                     timestamp with local time zone default on null current_timestamp not null
  , updated_by                     varchar2(60 char)
  , updated_on                     timestamp with local time zone
);

-- Index to quickly fetch matches by round
create index wmg_matches_idx on wmg_matches (tournament_id, round_number, match_number);

comment on table wmg_matches is 'Matches between two teams';

create or replace trigger wmg_matches_bu
    before update 
    on wmg_matches
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_matches_bu;
/
