create table wmg_rounds (
    id                             number generated by default on null as identity 
                                   constraint rounds_id_pk primary key,
    tournament_session_id          number not null
                                   constraint wmg_round_tournament_sess_fk
                                   references wmg_tournament_sessions(id),
    week                           varchar2(10) constraint wmg_rouund_week_ck check (regexp_like(week, 'S[0-9]+W[0-9]+')),
    course_id                      number not null
                                   constraint wmg_rounds_course_id_fk
                                   references wmg_courses on delete cascade,
    players_id                     number
                                   constraint wmg_rounds_players_id_fk
                                   references wmg_players on delete cascade,
    round_played_on                timestamp with local time zone,
    room_name                      varchar2(255 char),
    s1                             integer,
    s2                             integer,
    s3                             integer,
    s4                             integer,
    s5                             integer,
    s6                             integer,
    s7                             integer,
    s8                             integer,
    s9                             integer,
    s10                            integer,
    s11                            integer,
    s12                            integer,
    s13                            integer,
    s14                            integer,
    s15                            integer,
    s16                            integer,
    s17                            integer,
    s18                            integer,
    final_score                    integer,
    override_score                 integer,
    override_reason                varchar2(500),
    override_by                    varchar2(60 char),
    override_on                    timestamp with local time zone,
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

-- table index
create index wmg_rounds_i1 on wmg_rounds (course_id);
create index wmg_rounds_i2 on wmg_rounds (players_id);
create index wmg_rounds_01 on wmg_rounds (week);

alter table wmg_rounds add constraint
wmg_rounds_one_uk unique (players_id,week,course_id)
/

-- comments
comment on table wmg_rounds is 'Rounds by a player on a specific course';
comment on column wmg_rounds.s1 is 'hole 1 score';
comment on column wmg_rounds.s10 is 'hole 10 score';
comment on column wmg_rounds.s11 is 'hole 11 score';
comment on column wmg_rounds.s12 is 'hole 12 score';
comment on column wmg_rounds.s13 is 'hole 13 score';
comment on column wmg_rounds.s14 is 'hole 14 score';
comment on column wmg_rounds.s15 is 'hole 15 score';
comment on column wmg_rounds.s16 is 'hole 16 score';
comment on column wmg_rounds.s17 is 'hole 17 score';
comment on column wmg_rounds.s18 is 'hole 18 score';
comment on column wmg_rounds.s2 is 'hole 2 score';
comment on column wmg_rounds.s3 is 'hole 3 score';
comment on column wmg_rounds.s4 is 'hole 4 score';
comment on column wmg_rounds.s5 is 'hole 5 score';
comment on column wmg_rounds.s6 is 'hole 6 score';
comment on column wmg_rounds.s7 is 'hole 7 score';
comment on column wmg_rounds.s8 is 'hole 8 score';
comment on column wmg_rounds.s9 is 'hole 9 score';

comment on column wmg_rounds.final_score is 'Score submitted by the player';
comment on column wmg_rounds.override_score is 'Score entered by an admin';
comment on column wmg_rounds.override_reason is 'Reason for the admin to change the score';
comment on column wmg_rounds.override_by is 'Person entering the override';
comment on column wmg_rounds.override_on is 'Date the override was entered';
