-- drop table wmg_course_vote cascade constraints purge;

-- Keep table names under 24 characters
--           1234567890123456789012345
create table wmg_course_vote (
    id            number        generated by default on null as identity (start with 1) primary key not null
  , course_id     number        not null constraint wmg_vote_course_fk references wmg_courses(id)
  , player_id     number        not null constraint wmg_vote_player_fk references wmg_players(id)
  , vote          number        not null
  , created_on                     timestamp with local time zone default on null current_timestamp not null
  , created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
  , updated_on                     timestamp with local time zone
  , updated_by                     varchar2(60 char)
)
enable primary key using index
/

comment on table wmg_course_vote is 'Register player votes on a course';

create unique index wmg_course_vote_u01 on wmg_course_vote(course_id, player_id); -- only ONE vote per player per course

comment on column wmg_course_vote.id is 'Primary Key ID';
comment on column wmg_course_vote.course_id is 'Course voted on';
comment on column wmg_course_vote.player_id is 'Player that voted on a course';
comment on column wmg_course_vote.vote is '1 = vote up, 0 = vote removed, -1 vote down';
comment on column wmg_course_vote.created_by is 'User that created this record';
comment on column wmg_course_vote.created_on is 'Date the record was first created';
comment on column wmg_course_vote.updated_by is 'User that last modified this record';
comment on column wmg_course_vote.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger wmg_course_vote_u
--------------------------------------------------------
create or replace trigger wmg_course_vote_u
before update
on wmg_course_vote
referencing old as old new as new
for each row
begin
  if updating then
    :new.updated_on := sysdate;
    :new.updated_by := coalesce(
                        sys_context('APEX$SESSION','app_user')
                      , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                      , sys_context('userenv','session_user')
                    );
  end if;
end;
/
