-- drop table wmg_messages cascade constraints purge;

-- Keep table names under 24 characters
--           1234567890123456789012345
create table wmg_messages (
    id                             number generated by default on null as identity 
                                   constraint messages_id_pk primary key
  , to_player_id     number        not null
                                   constraint wmg_messages_to_player_i_fk
                                   references wmg_players(id)
  , message_from     varchar2(60 char) not null
  , message          varchar2(4000 char)    not null
  , display_count    number default on null 0
  , new_message_ind  varchar2(1)    default on null 'Y' not null
  , display_mode     varchar2(10)   default on null 'POPUP' not null 
  , message_date     timestamp with time zone default on null current_timestamp not null
  , created_on                     timestamp with local time zone default on null current_timestamp not null
  , created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
  , updated_on                     timestamp with local time zone
  , updated_by                     varchar2(60 char)
  , constraint wmg_messages_ck_display_mode
      check (display_mode in ('POPUP', 'BANNER'))
  , constraint wmg_messages_ck_new
      check (new_message_ind in ('Y', 'N'))
)
enable primary key using index
/

comment on table wmg_messages is 'List of wmg_messages';

comment on column wmg_messages.id is 'Primary Key ID';
comment on column wmg_messages.display_count is 'Times the message has been displayed to the player';
comment on column wmg_messages.display_mode is 'Displays the message as a popup in full screen mode';
comment on column wmg_messages.created_by is 'User that created this record';
comment on column wmg_messages.created_on is 'Date the record was first created';
comment on column wmg_messages.updated_by is 'User that last modified this record';
comment on column wmg_messages.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger wmg_messages_bu
--------------------------------------------------------
create or replace trigger wmg_messages_bu
before update
on wmg_messages
referencing old as old new as new
for each row
begin
  if updating then
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
  end if;
end wmg_messages_bu;
/
