-- drop objects
-- drop table wmg_badge_types cascade constraints;

-- create tables
create table wmg_badge_types (
    id                             number generated by default on null as identity 
                                   constraint wmg_badge_types_id_pk primary key,
    code                           varchar2(10 char)
                                   constraint wmg_badge_types_code_unq unique not null,
    name                           varchar2(20 char)
                                   constraint wmg_badge_types_name_unq unique not null,
    display_seq                    integer not null,
    description                    varchar2(4000 char),
    icon_class                     varchar2(100 char),
    system_calculated_ind          varchar2(1 char) default 'N' constraint wmg_badge_types_sys_ind_ck
                                   check (system_calculated_ind in ('Y','N')) not null,
    active_ind                     varchar2(1 char) default 'Y' constraint wmg_badge_types_active_ind_ck
                                   check (active_ind in ('Y','N')) not null,
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(255 char)
)
;

comment on table wmg_badge_types is 'Badges that a player can earn';

-- triggers
create or replace trigger wmg_badge_types_bu
    before update 
    on wmg_badge_types
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_badge_types_bu;
/
