create table wmg_course_strokes (
    id                             number generated by default on null as identity 
                                   constraint wmg_course_strokes_id_pk primary key,
    course_id                      number
                                   constraint wmg_course_strokes_course_id_fk
                                   references wmg_courses on delete cascade,
    h1                             integer not null,
    h2                             integer not null,
    h3                             integer not null,
    h4                             integer not null,
    h5                             integer not null,
    h6                             integer not null,
    h7                             integer not null,
    h8                             integer not null,
    h9                             integer not null,
    h10                            integer not null,
    h11                            integer not null,
    h12                            integer not null,
    h13                            integer not null,
    h14                            integer not null,
    h15                            integer not null,
    h16                            integer not null,
    h17                            integer not null,
    h18                            integer not null
)
;

-- table index
create index wmg_course_strokes_i1 on wmg_course_strokes (course_id);

-- comments
comment on table wmg_course_strokes is 'Par values for each hole on a course';
comment on column wmg_course_strokes.h1 is 'hole 1 par value';
comment on column wmg_course_strokes.h10 is 'hole 10 par value';
comment on column wmg_course_strokes.h11 is 'hole 11 par value';
comment on column wmg_course_strokes.h12 is 'hole 12 par value';
comment on column wmg_course_strokes.h13 is 'hole 13 par value';
comment on column wmg_course_strokes.h14 is 'hole 14 par value';
comment on column wmg_course_strokes.h15 is 'hole 15 par value';
comment on column wmg_course_strokes.h16 is 'hole 16 par value';
comment on column wmg_course_strokes.h17 is 'hole 17 par value';
comment on column wmg_course_strokes.h18 is 'hole 18 par value';
comment on column wmg_course_strokes.h2 is 'hole 2 par value';
comment on column wmg_course_strokes.h3 is 'hole 3 par value';
comment on column wmg_course_strokes.h4 is 'hole 4 par value';
comment on column wmg_course_strokes.h5 is 'hole 5 par value';
comment on column wmg_course_strokes.h6 is 'hole 6 par value';
comment on column wmg_course_strokes.h7 is 'hole 7 par value';
comment on column wmg_course_strokes.h8 is 'hole 8 par value';
comment on column wmg_course_strokes.h9 is 'hole 9 par value';
