
-- drop table wmg_player_unicorns cascade constraints;

create table wmg_player_unicorns (
    id                             number generated by default on null as identity 
                                   constraint wmg_player_unicorns_id_pk primary key,
    course_id                      number not null
                                   constraint wmg_player_uni_course_fk
                                   references wmg_courses(id),
    player_id                      number
                                   constraint wmg_player_unicorns_player_id_fk
                                   references wmg_players(id) on delete cascade,
    h                              integer default 0,
    attempt_count                  number,
    score_tournament_session_id    number not null
                                   constraint wmg_player_tournament_score_unicorn_fk
                                   references wmg_tournament_sessions(id) on delete cascade,
    award_tournament_session_id    number not null
                                   constraint wmg_player_tournament_award_unicorn_fk
                                   references wmg_tournament_sessions(id) on delete cascade,
    repeat_count                   number,
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(255 char)
)
;

comment on table wmg_player_unicorns is 'Earned ace unicorns';
comment on column wmg_player_unicorns.attempt_count is 'Times the hole was played before';
comment on column wmg_player_unicorns.score_tournament_session_id is 'When did the unicorn occur';
comment on column wmg_player_unicorns.award_tournament_session_id is 'When was the unicorn awarded';
comment on column wmg_player_unicorns.repeat_count is 'Number of times this unicorn has been repated';

-- table index
create unique index wmg_player_unicorns_u01 on wmg_player_unicorns (course_id, player_id, h);
create index wmg_player_unicorns_i01 on wmg_player_unicorns (player_id);

create or replace trigger wmg_player_unicorns_bu
    before insert or update 
    on wmg_player_unicorns
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_player_unicorns_bu;
/
