
drop table wmg_player_badges cascade constraints;

create table wmg_player_badges (
    id                             number generated by default on null as identity 
                                   constraint wmg_player_badges_id_pk primary key,
    badge_type_code                varchar2(10)
                                   constraint wmg_player_badge_typ_fk
                                   references wmg_badge_types(code) on delete cascade,
    tournament_session_id          number
                                   constraint wmg_player_tournament_badge_fk
                                   references wmg_tournament_sessions(id) on delete cascade,
    player_id                      number
                                   constraint wmg_player_badges_player_id_fk
                                   references wmg_players(id) on delete cascade,
    badge_count                    integer default 0,
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(255 char)
)
;

-- table index
create unique index wmg_player_badges_u01 on wmg_player_badges (player_id, badge_type_code, tournament_session_id);
create index wmg_player_badges_i01 on wmg_player_badges (tournament_session_id);
-- create index wmg_player_badges_i02 on wmg_player_badges (badge_type_code);

create or replace trigger wmg_player_badges_bu
    before insert or update 
    on wmg_player_badges
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_player_badges_bu;
/
