
-- drop table wmg_languages purge;

create table wmg_languages (
    id            number             generated by default on null as identity (start with 1) primary key not null
  , display_seq   number             not null
  , code          varchar2(10 char)  not null
  , name          varchar2(32 char)
  , installed_ind varchar2(1)        not null
  , active_ind    varchar2(1)        not null
  , created_by    varchar2(60 char)  not null
  , created_on    date               not null
  , updated_by    varchar2(60 char)
  , updated_on    date
  , constraint wmg_languages_ck_ins
      check (installed_ind in ('Y', 'N'))
  , constraint wmg_languages_ck_active
      check (active_ind in ('Y', 'N'))
  , constraint wmg_languages_u unique (code)
)
enable primary key using index
/

comment on table wmg_languages is 'List of  Application languages';

comment on column wmg_languages.display_seq is 'Order for displaying the languages';
comment on column wmg_languages.code is 'Language Code';
comment on column wmg_languages.name is 'Name of language as the user will see it';
comment on column wmg_languages.installed_ind is 'Is the language in use by the application Y/N?';
comment on column wmg_languages.active_ind is 'Is the record enabled Y/N?';
comment on column wmg_languages.created_by is 'User that created this record';
comment on column wmg_languages.created_on is 'Date the record was first created';
comment on column wmg_languages.updated_by is 'User that last modified this record';
comment on column wmg_languages.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger wmg_languages_iu
--------------------------------------------------------
create or replace trigger wmg_languages_iu
before insert or update
on wmg_languages
referencing old as old new as new
for each row
begin
  if inserting then

    :new.created_on := sysdate;
    :new.created_by := coalesce(
                        sys_context('APEX$SESSION','app_user')
                      , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                      , sys_context('userenv','session_user')
                    );

  elsif updating then

    :new.updated_on := sysdate;
    :new.updated_by := coalesce(
                           sys_context('APEX$SESSION','app_user')
                         , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                         , sys_context('userenv','session_user')
                       );
  end if;
end;
/
