-- drop table wmg_promos;

create table wmg_promos (
    id                             number generated by default on null as identity 
                                   constraint wmg_promos_id_pk primary key
  , code               varchar2(100)
  , image_preview      blob
  , mimetype           varchar2(255)
  , filename           varchar2(400)
  , image_last_update  timestamp (6) with local time zone
  , active_ind         varchar2(1)   not null
  , created_on         timestamp with local time zone default on null current_timestamp not null
  , created_by         varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null
  , updated_on         timestamp with local time zone
  , updated_by         varchar2(60 char)
)
;

-- table index
create unique index wmg_promos_u01 on wmg_promos (code);

-- comments
comment on table wmg_promos is 'Preview images per hole';


-- triggers
create or replace trigger wmg_promos_bu
    before update 
    on wmg_promos
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_promos_bu;
/
