-- create tables
create table wmg_players (
    id                             number generated by default on null as identity 
                                   constraint players_id_pk primary key,
    account                        varchar2(32 char),
    name                           varchar2(60 char)
)
;

create unique index wmg_players_u01 on wmg_players (lower(account));
create unique index wmg_players_u01 on wmg_players (lower(name));

-- comments
comment on column players.account is 'discord name';

create table wmg_courses (
    id                             number generated by default on null as identity 
                                   constraint courses_id_pk primary key,
    code                           varchar2(5 char)
                                   constraint courses_code_unq unique,
    name                           varchar2(255 char) not null,
    course_mode                    varchar2(1 char) constraint courses_course_mode_ck
                                   check (course_mode in ('E','H'))
)
;

create table wmg_rounds (
    id                             number generated by default on null as identity 
                                   constraint rounds_id_pk primary key,
    week                           varchar2(10) constraint check (regexp_like(week, 'S[0-9]+W[0-9]+')),
    course_id                      number
                                   constraint rounds_course_id_fk
                                   references courses on delete cascade,
    players_id                     number
                                   constraint rounds_players_id_fk
                                   references players on delete cascade,
    round_played_on                timestamp with local time zone,
    room_name                      varchar2(255 char),
    s1                             integer,
    s2                             integer,
    s3                             integer,
    s4                             integer,
    s5                             integer,
    s6                             integer,
    s7                             integer,
    s8                             integer,
    s9                             integer,
    s10                            integer,
    s11                            integer,
    s12                            integer,
    s13                            integer,
    s14                            integer,
    s15                            integer,
    s16                            integer,
    s17                            integer,
    s18                            integer
)
;

-- table index
create index rounds_i1 on wmg_rounds (course_id);
create index rounds_i2 on wmg_rounds (players_id);
create index rounds_01 on wmg_rounds (week);

alter table wmg_rounds add constraint
rounds_one_uk unique (players_id,week,course_id)
/

-- comments
comment on table rounds is 'Rounds by a player on a specific course';
comment on column rounds.s1 is 'hole 1 score';
comment on column rounds.s10 is 'hole 10 score';
comment on column rounds.s11 is 'hole 11 score';
comment on column rounds.s12 is 'hole 12 score';
comment on column rounds.s13 is 'hole 13 score';
comment on column rounds.s14 is 'hole 14 score';
comment on column rounds.s15 is 'hole 15 score';
comment on column rounds.s16 is 'hole 16 score';
comment on column rounds.s17 is 'hole 17 score';
comment on column rounds.s18 is 'hole 18 score';
comment on column rounds.s2 is 'hole 2 score';
comment on column rounds.s3 is 'hole 3 score';
comment on column rounds.s4 is 'hole 4 score';
comment on column rounds.s5 is 'hole 5 score';
comment on column rounds.s6 is 'hole 6 score';
comment on column rounds.s7 is 'hole 7 score';
comment on column rounds.s8 is 'hole 8 score';
comment on column rounds.s9 is 'hole 9 score';

create table wmg_course_strokes (
    id                             number generated by default on null as identity 
                                   constraint course_strokes_id_pk primary key,
    course_id                      number
                                   constraint course_strokes_course_id_fk
                                   references courses on delete cascade,
    h1                             integer not null,
    h2                             integer not null,
    h3                             integer not null,
    h4                             integer not null,
    h5                             integer not null,
    h6                             integer not null,
    h7                             integer not null,
    h8                             integer not null,
    h9                             integer not null,
    h10                            integer not null,
    h11                            integer not null,
    h12                            integer not null,
    h13                            integer not null,
    h14                            integer not null,
    h15                            integer not null,
    h16                            integer not null,
    h17                            integer not null,
    h18                            integer not null
)
;

-- table index
create index course_strokes_i1 on course_strokes (course_id);

-- comments
comment on table course_strokes is 'Par values for each hole on a course';
comment on column course_strokes.h1 is 'hole 1 par value';
comment on column course_strokes.h10 is 'hole 10 par value';
comment on column course_strokes.h11 is 'hole 11 par value';
comment on column course_strokes.h12 is 'hole 12 par value';
comment on column course_strokes.h13 is 'hole 13 par value';
comment on column course_strokes.h14 is 'hole 14 par value';
comment on column course_strokes.h15 is 'hole 15 par value';
comment on column course_strokes.h16 is 'hole 16 par value';
comment on column course_strokes.h17 is 'hole 17 par value';
comment on column course_strokes.h18 is 'hole 18 par value';
comment on column course_strokes.h2 is 'hole 2 par value';
comment on column course_strokes.h3 is 'hole 3 par value';
comment on column course_strokes.h4 is 'hole 4 par value';
comment on column course_strokes.h5 is 'hole 5 par value';
comment on column course_strokes.h6 is 'hole 6 par value';
comment on column course_strokes.h7 is 'hole 7 par value';
comment on column course_strokes.h8 is 'hole 8 par value';
comment on column course_strokes.h9 is 'hole 9 par value';


-- create views
create or replace view course_v as 
select 
    courses.id                                         course_id,
    courses.code                                       code,
    courses.name                                       name,
    courses.course_mode                                course_mode,
    course_strokes.id                                  course_stroke_id,
    course_strokes.h1                                  h1,
    course_strokes.h2                                  h2,
    course_strokes.h3                                  h3,
    course_strokes.h4                                  h4,
    course_strokes.h5                                  h5,
    course_strokes.h6                                  h6,
    course_strokes.h7                                  h7,
    course_strokes.h8                                  h8,
    course_strokes.h9                                  h9,
    course_strokes.h10                                 h10,
    course_strokes.h11                                 h11,
    course_strokes.h12                                 h12,
    course_strokes.h13                                 h13,
    course_strokes.h14                                 h14,
    course_strokes.h15                                 h15,
    course_strokes.h16                                 h16,
    course_strokes.h17                                 h17,
    course_strokes.h18                                 h18
from 
    courses,
    course_strokes
where
    course_strokes.course_id(+) = courses.id
/

create or replace view rounds_v as 
select 
    players.id                                         player_id,
    players.account                                    account,
    players.name                                       player_name,
    courses.id                                         course_id,
    courses.code                                       code,
    courses.name                                       course_name,
    courses.course_mode                                course_mode,
    course_strokes.id                                  course_stroke_id,
    course_strokes.h1                                  h1,
    course_strokes.h2                                  h2,
    course_strokes.h3                                  h3,
    course_strokes.h4                                  h4,
    course_strokes.h5                                  h5,
    course_strokes.h6                                  h6,
    course_strokes.h7                                  h7,
    course_strokes.h8                                  h8,
    course_strokes.h9                                  h9,
    course_strokes.h10                                 h10,
    course_strokes.h11                                 h11,
    course_strokes.h12                                 h12,
    course_strokes.h13                                 h13,
    course_strokes.h14                                 h14,
    course_strokes.h15                                 h15,
    course_strokes.h16                                 h16,
    course_strokes.h17                                 h17,
    course_strokes.h18                                 h18,
    rounds.id                                          round_id,
    rounds.round_played_on                             round_played_on,
    rounds.room_name                                   room_name,
    rounds.s1                                          s1,
    rounds.s2                                          s2,
    rounds.s3                                          s3,
    rounds.s4                                          s4,
    rounds.s5                                          s5,
    rounds.s6                                          s6,
    rounds.s7                                          s7,
    rounds.s8                                          s8,
    rounds.s9                                          s9,
    rounds.s10                                         s10,
    rounds.s11                                         s11,
    rounds.s12                                         s12,
    rounds.s13                                         s13,
    rounds.s14                                         s14,
    rounds.s15                                         s15,
    rounds.s16                                         s16,
    rounds.s17                                         s17,
    rounds.s18                                         s18
from 
    players,
    courses,
    course_strokes,
    rounds
where
    rounds.course_id(+) = courses.id and
    course_strokes.course_id(+) = courses.id
/

-- load data
 
insert into players (
    id,
    account,
    name
) values (
    1,
    'Lorem Commodo Ullamcorperinterdu',
    'Business Rules Engine Implementation'
);

insert into players (
    id,
    account,
    name
) values (
    2,
    'Placerat Iaculis Aliquam',
    'Serverless Upgrade'
);

insert into players (
    id,
    account,
    name
) values (
    3,
    'Tristique Ac Volutpat',
    'Build System Upgrade'
);

insert into players (
    id,
    account,
    name
) values (
    4,
    'Dictum Lorem Sit',
    'New Mortem'
);

insert into players (
    id,
    account,
    name
) values (
    5,
    'Amet Massa Eu',
    'Datalogic System'
);

insert into players (
    id,
    account,
    name
) values (
    6,
    'Lorem Sit Amet',
    'Inventory Management'
);

insert into players (
    id,
    account,
    name
) values (
    7,
    'Amet Massa Eu',
    'Entrepreneur Program Review'
);

insert into players (
    id,
    account,
    name
) values (
    8,
    'Sit Amet Imperdiet',
    'JIRA Ticketing System Migration'
);

insert into players (
    id,
    account,
    name
) values (
    9,
    'Nulla Placerat Iaculis',
    'World Analysis'
);

insert into players (
    id,
    account,
    name
) values (
    10,
    'Amet Lectus Nulla',
    'Build Automation'
);

commit;
 
-- load data
-- load data
 
insert into courses (
    id,
    code,
    name,
    course_mode
) values (
    1,
    'x',
    'Business Rules Engine Implementation',
    'E'
);

insert into courses (
    id,
    code,
    name,
    course_mode
) values (
    2,
    'x',
    'Serverless Upgrade',
    'H'
);

commit;
 
-- load data
 
insert into rounds (
    id,
    course_id,
    players_id,
    round_played_on,
    room_name,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    s8,
    s9,
    s10,
    s11,
    s12,
    s13,
    s14,
    s15,
    s16,
    s17,
    s18
) values (
    1,
    2,
    1,
    cast(add_months(systimestamp,-5) as timestamp with local time zone),
    'Business Rules Engine Implementation',
    71,
    56,
    41,
    91,
    22,
    1,
    45,
    69,
    20,
    85,
    86,
    27,
    57,
    48,
    7,
    75,
    64,
    71
);

insert into rounds (
    id,
    course_id,
    players_id,
    round_played_on,
    room_name,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    s8,
    s9,
    s10,
    s11,
    s12,
    s13,
    s14,
    s15,
    s16,
    s17,
    s18
) values (
    2,
    1,
    1,
    cast(add_months(systimestamp,-7) as timestamp with local time zone),
    'Serverless Upgrade',
    83,
    53,
    81,
    82,
    20,
    72,
    28,
    3,
    47,
    65,
    85,
    72,
    23,
    42,
    52,
    63,
    22,
    71
);

insert into rounds (
    id,
    course_id,
    players_id,
    round_played_on,
    room_name,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    s8,
    s9,
    s10,
    s11,
    s12,
    s13,
    s14,
    s15,
    s16,
    s17,
    s18
) values (
    3,
    2,
    1,
    cast(add_months(systimestamp,-3) as timestamp with local time zone),
    'Build System Upgrade',
    50,
    46,
    40,
    82,
    73,
    98,
    5,
    94,
    33,
    44,
    41,
    42,
    90,
    47,
    59,
    21,
    92,
    81
);

insert into rounds (
    id,
    course_id,
    players_id,
    round_played_on,
    room_name,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    s8,
    s9,
    s10,
    s11,
    s12,
    s13,
    s14,
    s15,
    s16,
    s17,
    s18
) values (
    4,
    1,
    1,
    cast(add_months(systimestamp,-5) as timestamp with local time zone),
    'New Mortem',
    27,
    29,
    9,
    16,
    80,
    61,
    39,
    93,
    98,
    3,
    65,
    79,
    81,
    16,
    54,
    35,
    32,
    69
);

insert into rounds (
    id,
    course_id,
    players_id,
    round_played_on,
    room_name,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    s8,
    s9,
    s10,
    s11,
    s12,
    s13,
    s14,
    s15,
    s16,
    s17,
    s18
) values (
    5,
    1,
    1,
    cast(add_months(systimestamp,-2) as timestamp with local time zone),
    'Datalogic System',
    96,
    76,
    89,
    18,
    50,
    98,
    8,
    44,
    63,
    51,
    11,
    30,
    18,
    1,
    7,
    38,
    79,
    47
);

insert into rounds (
    id,
    course_id,
    players_id,
    round_played_on,
    room_name,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    s8,
    s9,
    s10,
    s11,
    s12,
    s13,
    s14,
    s15,
    s16,
    s17,
    s18
) values (
    6,
    1,
    1,
    cast(add_months(systimestamp,-6) as timestamp with local time zone),
    'Inventory Management',
    53,
    11,
    30,
    82,
    69,
    86,
    14,
    77,
    95,
    55,
    28,
    44,
    13,
    20,
    91,
    96,
    17,
    66
);

insert into rounds (
    id,
    course_id,
    players_id,
    round_played_on,
    room_name,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    s8,
    s9,
    s10,
    s11,
    s12,
    s13,
    s14,
    s15,
    s16,
    s17,
    s18
) values (
    7,
    1,
    1,
    cast(add_months(systimestamp,-7) as timestamp with local time zone),
    'Entrepreneur Program Review',
    47,
    6,
    2,
    57,
    18,
    87,
    65,
    30,
    20,
    77,
    86,
    52,
    45,
    93,
    25,
    9,
    73,
    3
);

insert into rounds (
    id,
    course_id,
    players_id,
    round_played_on,
    room_name,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    s8,
    s9,
    s10,
    s11,
    s12,
    s13,
    s14,
    s15,
    s16,
    s17,
    s18
) values (
    8,
    1,
    1,
    cast(add_months(systimestamp,-5) as timestamp with local time zone),
    'JIRA Ticketing System Migration',
    25,
    57,
    31,
    12,
    100,
    42,
    92,
    99,
    27,
    66,
    91,
    90,
    13,
    19,
    42,
    34,
    84,
    13
);

insert into rounds (
    id,
    course_id,
    players_id,
    round_played_on,
    room_name,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    s8,
    s9,
    s10,
    s11,
    s12,
    s13,
    s14,
    s15,
    s16,
    s17,
    s18
) values (
    9,
    1,
    1,
    cast(add_months(systimestamp,-2) as timestamp with local time zone),
    'World Analysis',
    32,
    8,
    46,
    98,
    68,
    55,
    38,
    75,
    72,
    45,
    83,
    55,
    61,
    84,
    34,
    54,
    11,
    78
);

insert into rounds (
    id,
    course_id,
    players_id,
    round_played_on,
    room_name,
    s1,
    s2,
    s3,
    s4,
    s5,
    s6,
    s7,
    s8,
    s9,
    s10,
    s11,
    s12,
    s13,
    s14,
    s15,
    s16,
    s17,
    s18
) values (
    10,
    1,
    1,
    cast(add_months(systimestamp,-1) as timestamp with local time zone),
    'Build Automation',
    38,
    83,
    29,
    58,
    9,
    17,
    93,
    91,
    79,
    52,
    78,
    33,
    55,
    91,
    76,
    17,
    78,
    1
);

commit;
 
-- load data
 
insert into course_strokes (
    id,
    course_id,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    h7,
    h8,
    h9,
    h10,
    h11,
    h12,
    h13,
    h14,
    h15,
    h16,
    h17,
    h18
) values (
    1,
    1,
    20,
    35,
    34,
    39,
    5,
    64,
    17,
    46,
    93,
    74,
    4,
    74,
    86,
    17,
    5,
    51,
    10,
    30
);

insert into course_strokes (
    id,
    course_id,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    h7,
    h8,
    h9,
    h10,
    h11,
    h12,
    h13,
    h14,
    h15,
    h16,
    h17,
    h18
) values (
    2,
    1,
    68,
    88,
    90,
    43,
    22,
    47,
    69,
    93,
    6,
    52,
    39,
    89,
    14,
    93,
    87,
    55,
    86,
    18
);

commit;
 
 
-- Generated by Quick SQL Thursday September 08, 2022  22:18:39
 
/*
players /insert 10
  account vc32 -- discord name
  name    vc60
courses /insert 2
    code vc5 /unique
    name /nn
    course mode /check E H
    rounds  /insert 10 -- Rounds by a player on a specific course
      players_id /fk players id
      round_played_on tsltz
      room_name
      s1 int -- hole 1 score
      s2 int -- hole 2 score
      s3 int -- hole 3 score
      s4 int -- hole 4 score
      s5 int -- hole 5 score
      s6 int -- hole 6 score
      s7 int -- hole 7 score
      s8 int -- hole 8 score
      s9 int -- hole 9 score
      s10 int -- hole 10 score
      s11 int -- hole 11 score
      s12 int -- hole 12 score
      s13 int -- hole 13 score
      s14 int -- hole 14 score
      s15 int -- hole 15 score
      s16 int -- hole 16 score
      s17 int -- hole 17 score
      s18 int -- hole 18 score
    course_strokes /insert 2 -- Par values for each hole on a course
      h1 int /nn -- hole 1 par value
      h2 int /nn -- hole 2 par value
      h3 int /nn -- hole 3 par value
      h4 int /nn -- hole 4 par value
      h5 int /nn -- hole 5 par value
      h6 int /nn -- hole 6 par value
      h7 int /nn -- hole 7 par value
      h8 int /nn -- hole 8 par value
      h9 int /nn -- hole 9 par value
      h10 int /nn -- hole 10 par value
      h11 int /nn -- hole 11 par value
      h12 int /nn -- hole 12 par value
      h13 int /nn -- hole 13 par value
      h14 int /nn -- hole 14 par value
      h15 int /nn -- hole 15 par value
      h16 int /nn -- hole 16 par value
      h17 int /nn -- hole 17 par value
      h18 int /nn -- hole 18 par value

view course_v courses course_strokes
view rounds_v players courses course_strokes rounds

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
