-- create tables
create table wmg_players (
    id                             number generated by default on null as identity 
                                   constraint players_id_pk primary key,
    account                        varchar2(32 char),
    name                           varchar2(60 char),
    discord_id                     number,
    discord_avatar                 varchar2(62),
    discord_discriminator          varchar2(10),
    account_login                  varchar2(100),
    prefered_tz                    varchar2(20),
    country_code                   varchar2(5),
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

create unique index wmg_players_u01 on wmg_players (lower(account));
create unique index wmg_players_u02 on wmg_players (lower(name));

-- comments
comment on column wmg_players.account is 'discord name';

create table wmg_courses (
    id                             number generated by default on null as identity 
                                   constraint courses_id_pk primary key,
    code                           varchar2(5 char)
                                   constraint courses_code_unq unique,
    name                           varchar2(255 char) not null,
    course_mode                    varchar2(1 char) constraint courses_course_mode_ck
                                   check (course_mode in ('E','H')),
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

create table wmg_rounds (
    id                             number generated by default on null as identity 
                                   constraint rounds_id_pk primary key,
    week                           varchar2(10) constraint wmg_rouund_week_ck check (regexp_like(week, 'S[0-9]+W[0-9]+')),
    course_id                      number
                                   constraint wmg_rounds_course_id_fk
                                   references wmg_courses on delete cascade,
    players_id                     number
                                   constraint wmg_rounds_players_id_fk
                                   references wmg_players on delete cascade,
    round_played_on                timestamp with local time zone,
    room_name                      varchar2(255 char),
    s1                             integer,
    s2                             integer,
    s3                             integer,
    s4                             integer,
    s5                             integer,
    s6                             integer,
    s7                             integer,
    s8                             integer,
    s9                             integer,
    s10                            integer,
    s11                            integer,
    s12                            integer,
    s13                            integer,
    s14                            integer,
    s15                            integer,
    s16                            integer,
    s17                            integer,
    s18                            integer,
    final_score                    integer,
    override_reason                varchar2(500),
    override_by                    varchar2(60 char),
    override_on                    timestamp with local time zone,    
    created_on                     timestamp with local time zone default on null current_timestamp not null,
    created_by                     varchar2(60 char) default on null coalesce(sys_context('APEX$SESSION','APP_USER'),user) not null,
    updated_on                     timestamp with local time zone,
    updated_by                     varchar2(60 char)
)
;

-- table index
create index wmg_rounds_i1 on wmg_rounds (course_id);
create index wmg_rounds_i2 on wmg_rounds (players_id);
create index wmg_rounds_01 on wmg_rounds (week);

alter table wmg_rounds add constraint
wmg_rounds_one_uk unique (players_id,week,course_id)
/

-- comments
comment on table wmg_rounds is 'Rounds by a player on a specific course';
comment on column wmg_rounds.s1 is 'hole 1 score';
comment on column wmg_rounds.s10 is 'hole 10 score';
comment on column wmg_rounds.s11 is 'hole 11 score';
comment on column wmg_rounds.s12 is 'hole 12 score';
comment on column wmg_rounds.s13 is 'hole 13 score';
comment on column wmg_rounds.s14 is 'hole 14 score';
comment on column wmg_rounds.s15 is 'hole 15 score';
comment on column wmg_rounds.s16 is 'hole 16 score';
comment on column wmg_rounds.s17 is 'hole 17 score';
comment on column wmg_rounds.s18 is 'hole 18 score';
comment on column wmg_rounds.s2 is 'hole 2 score';
comment on column wmg_rounds.s3 is 'hole 3 score';
comment on column wmg_rounds.s4 is 'hole 4 score';
comment on column wmg_rounds.s5 is 'hole 5 score';
comment on column wmg_rounds.s6 is 'hole 6 score';
comment on column wmg_rounds.s7 is 'hole 7 score';
comment on column wmg_rounds.s8 is 'hole 8 score';
comment on column wmg_rounds.s9 is 'hole 9 score';

create table wmg_course_strokes (
    id                             number generated by default on null as identity 
                                   constraint wmg_course_strokes_id_pk primary key,
    course_id                      number
                                   constraint wmg_course_strokes_course_id_fk
                                   references wmg_courses on delete cascade,
    h1                             integer not null,
    h2                             integer not null,
    h3                             integer not null,
    h4                             integer not null,
    h5                             integer not null,
    h6                             integer not null,
    h7                             integer not null,
    h8                             integer not null,
    h9                             integer not null,
    h10                            integer not null,
    h11                            integer not null,
    h12                            integer not null,
    h13                            integer not null,
    h14                            integer not null,
    h15                            integer not null,
    h16                            integer not null,
    h17                            integer not null,
    h18                            integer not null
)
;

-- table index
create index wmg_course_strokes_i1 on wmg_course_strokes (course_id);

-- comments
comment on table wmg_course_strokes is 'Par values for each hole on a course';
comment on column wmg_course_strokes.h1 is 'hole 1 par value';
comment on column wmg_course_strokes.h10 is 'hole 10 par value';
comment on column wmg_course_strokes.h11 is 'hole 11 par value';
comment on column wmg_course_strokes.h12 is 'hole 12 par value';
comment on column wmg_course_strokes.h13 is 'hole 13 par value';
comment on column wmg_course_strokes.h14 is 'hole 14 par value';
comment on column wmg_course_strokes.h15 is 'hole 15 par value';
comment on column wmg_course_strokes.h16 is 'hole 16 par value';
comment on column wmg_course_strokes.h17 is 'hole 17 par value';
comment on column wmg_course_strokes.h18 is 'hole 18 par value';
comment on column wmg_course_strokes.h2 is 'hole 2 par value';
comment on column wmg_course_strokes.h3 is 'hole 3 par value';
comment on column wmg_course_strokes.h4 is 'hole 4 par value';
comment on column wmg_course_strokes.h5 is 'hole 5 par value';
comment on column wmg_course_strokes.h6 is 'hole 6 par value';
comment on column wmg_course_strokes.h7 is 'hole 7 par value';
comment on column wmg_course_strokes.h8 is 'hole 8 par value';
comment on column wmg_course_strokes.h9 is 'hole 9 par value';

-- triggers
create or replace trigger wmg_players_bu
    before update 
    on wmg_players
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_players_bu;
/

create or replace trigger wmg_rounds_bu
    before update 
    on wmg_rounds
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_rounds_bu;
/

create or replace trigger wmg_courses_bu
    before update 
    on wmg_courses
    for each row
begin
    :new.updated_on := current_timestamp;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end wmg_courses_bu;
/

 
-- Generated by Quick SQL Thursday September 08, 2022  22:18:39
 
/*
players /insert 10
  account vc32 -- discord name
  name    vc60
courses /insert 2
    code vc5 /unique
    name /nn
    course mode /check E H
    rounds  /insert 10 -- Rounds by a player on a specific course
      players_id /fk players id
      round_played_on tsltz
      room_name
      s1 int -- hole 1 score
      s2 int -- hole 2 score
      s3 int -- hole 3 score
      s4 int -- hole 4 score
      s5 int -- hole 5 score
      s6 int -- hole 6 score
      s7 int -- hole 7 score
      s8 int -- hole 8 score
      s9 int -- hole 9 score
      s10 int -- hole 10 score
      s11 int -- hole 11 score
      s12 int -- hole 12 score
      s13 int -- hole 13 score
      s14 int -- hole 14 score
      s15 int -- hole 15 score
      s16 int -- hole 16 score
      s17 int -- hole 17 score
      s18 int -- hole 18 score
    course_strokes /insert 2 -- Par values for each hole on a course
      h1 int /nn -- hole 1 par value
      h2 int /nn -- hole 2 par value
      h3 int /nn -- hole 3 par value
      h4 int /nn -- hole 4 par value
      h5 int /nn -- hole 5 par value
      h6 int /nn -- hole 6 par value
      h7 int /nn -- hole 7 par value
      h8 int /nn -- hole 8 par value
      h9 int /nn -- hole 9 par value
      h10 int /nn -- hole 10 par value
      h11 int /nn -- hole 11 par value
      h12 int /nn -- hole 12 par value
      h13 int /nn -- hole 13 par value
      h14 int /nn -- hole 14 par value
      h15 int /nn -- hole 15 par value
      h16 int /nn -- hole 16 par value
      h17 int /nn -- hole 17 par value
      h18 int /nn -- hole 18 par value

view course_v courses course_strokes
view rounds_v players courses course_strokes rounds

# settings = { semantics: "CHAR", language: "EN", APEX: true }
*/
