apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets
  namespace: wmgt-bot
type: Opaque
stringData:
  DISCORD_BOT_TOKEN: "your_production_bot_token_here"
  DISCORD_CLIENT_ID: "your_discord_client_id_here"
  DISCORD_GUILD_ID: "your_production_guild_id_here"
  API_BASE_URL: "https://apex.skillbuilders.com/ords/wmgt"
  LOG_LEVEL: "info"
  HEALTH_CHECK_ENABLED: "true"
  HEALTH_CHECK_PORT: "3000"
  MAX_CONCURRENT_REQUESTS: "10"
  REQUEST_TIMEOUT: "30000"
  RETRY_ATTEMPTS: "3"
  RETRY_DELAY: "1000"
  RATE_LIMIT_WINDOW: "60000"
  RATE_LIMIT_MAX_REQUESTS: "100"