apiVersion: v1
kind: Service
metadata:
  name: wmgt-discord-bot-service
  namespace: wmgt-bot
  labels:
    app: wmgt-discord-bot
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: health
    port: 3000
    targetPort: health
    protocol: TCP
  selector:
    app: wmgt-discord-bot