---
# ====== Application: WMGT ===================================
id: 200
identification: 
  name: WMGT
  alias: WMGT
  version: Release 2.6.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification
  error-handling-function: wmg_error_handler.error_handler_logging_session

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: false
  pass-ecid: N

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 46995003624569514326

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Enabled for Public Sessions

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Enabled
  embed-in-frames: Allow from same origin
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: WMGT

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: false

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Image and Text
  image-url: '&G_APP_FILES.icons/app-icon-192.png'
  text: <span class="hidden-xs-up">The </span>Weekly<span class="hidden-xxs-down"> Mini Golf Tournament</span>

progressive-web-app: 
  enable: true
  installable: true
  display: Fullscreen
  screen-orientation: Any
  ios-status-bar-style: Default
  app-description: Weekly Walkabout Mini Golf Tournament (WMGT) app
  custom-manifest: '{"name": "The Weekly"}'
  enable-push-notifications: true
  pwa-push-notifications-credentials: App 200 Push Notifications Credentials # 79419961897191954
  contact-email: jorge@rimblas.com

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&SESSION.'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Top Navigation Mega Menu
  template-options: 
  - '#DEFAULT#'
  list-position: Top
  list: Navigation Menu # 46995004465346514326

navigation-bar: 
  implementation: List
  list: Navigation Bar # 46995198593531514416
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  file-urls: 
  - '&G_APP_FILES.js/app#MIN#.js'
  include-jquery-migrate: false

css: 
  file-urls: 
  - '&G_APP_FILES.css/global#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: true
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 22456292862613002
  identification: 
    name: APP_NAME

  value: 
    static-value: WMGT

- # ====== Substitution: EDIT_BUTTON ===========================
  id: 22456292862613001
  identification: 
    name: EDIT_BUTTON

  value: 
    static-value: <span aria-label="Edit"><span class="fa fa-edit" aria-hidden="true" title="Edit"></span></span>

- # ====== Substitution: BUCKET ================================
  id: 22456292862613000
  identification: 
    name: BUCKET

  value: 
    static-value: 'https://objectstorage.us-ashburn-1.oraclecloud.com/n/idw1nygcxpvm/b/wmgt-assets/o/'

component-settings: 
- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 20475488134415100
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 1936709557

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 20475386515415100
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 1936709557

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 20475291702415100
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 1936709557

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 8784700892657470
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 40348156161857

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 11118864433703315
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 40348156184453

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 27516905235888134
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 40348156184456

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 46995000327182514324
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 40348156184456

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 46995000949694514324
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 40348156184456

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 46995001557258514325
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 40348156184457

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 46995001913973514325
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 40348156184460

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 46995002196784514325
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 40348156184460

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 46995002744093514325
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 40348156184466

- # ====== Component Setting: NATIVE_IR ========================
  id: 46995003046456514325
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 40348156184470

- # ====== Component Setting: PLUGIN_UC_NESTED_REPORTS =========
  id: 47496809529178607516
  identification: 
    name: PLUGIN_UC_NESTED_REPORTS
    type: Dynamic Action

  settings: 
    attribute-1: 200
    attribute-2: 400
    attribute-3: Y

  subscription: 
    version-number: 40348156184476

application-settings: 
- # ====== Application Setting: FEEDBACK_ATTACHMENTS_YN ========
  id: 46995204567167514426
  identification: 
    name: FEEDBACK_ATTACHMENTS_YN

  value: 
    value: Y
    required: false

  advanced: 
    valid-values: Y, N
    on-upgrade-keep-value: true

  subscription: 
    version-number: 40348156188364

  configuration: 
    build-option: 'Feature: Feedback' # 46995201057049514424

- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 46995204869433514426
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ALL_USERS
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  subscription: 
    version-number: 40348156188364

  configuration: 
    build-option: 'Feature: Access Control' # 46995200878247514424

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

