---
# ====== Application: WMGT ===================================
id: 200
identification: 
  name: WMGT
  alias: WMGT
  version: Release 2.05.0

row-search: 
  tokenize: true

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification
  error-handling-function: wmg_error_handler.error_handler_logging_session

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 / 22.1 / 22.2

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 46995003624569514326

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Enabled
  embed-in-frames: Allow from same origin
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: WKSP_WMGT

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Image and Text
  image-url: '&G_APP_FILES./icons/app-icon-192.png'
  text: Walkabout Mini Golf Tournament

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Black Text and White Background

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&SESSION.'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Top Navigation Mega Menu # 46995165177361514395
  template-options: 
  - '#DEFAULT#'
  list-position: Top
  list: Navigation Menu # 46995004465346514326

navigation-bar: 
  implementation: List
  list: Navigation Bar # 46995198593531514416
  list-template: Navigation Bar # 46995161346826514393
  template-options: 
  - '#DEFAULT#'

javascript: 
  file-urls: 
  - '&G_APP_FILES./js/app#MIN#.js'
  include-jquery-migrate: false

css: 
  file-urls: 
  - '&G_APP_FILES./css/global#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: true
  add-"built-with-apex"-to-footer: true

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: WMGT

- # ====== Substitution: EDIT_BUTTON ===========================
  id: 2
  identification: 
    name: EDIT_BUTTON

  value: 
    static-value: <span aria-label="Edit"><span class="fa fa-edit" aria-hidden="true" title="Edit"></span></span>

application-settings: 
- # ====== Application Setting: FEEDBACK_ATTACHMENTS_YN ========
  id: 46995204567167514426
  identification: 
    name: FEEDBACK_ATTACHMENTS_YN

  value: 
    value: Y
    required: false

  advanced: 
    valid-values: Y, N
    on-upgrade-keep-value: true

  configuration: 
    build-option: 'Feature: Feedback' # 46995201057049514424

- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 46995204869433514426
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ALL_USERS
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  configuration: 
    build-option: 'Feature: Access Control' # 46995200878247514424

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

