---
# ====== Application: WMGT ===================================
id: 127948
identification: 
  name: WMGT
  alias: WMGT
  version: Release 1.2

row-search: 
  tokenize: true

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification
  error-handling-function: wmg_error_handler.error_handler_logging_session

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 / 22.1 / 22.2

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 46986482701161702397

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: WKSP_WMGT

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Image and Text
  image-url: '#APP_FILES#img/26f3.svg'
  text: Walkabout Mini Golf Tournament

progressive-web-app: 
  enable: true
  installable: true
  display: Fullscreen
  screen-orientation: Landscape Primary
  ios-status-bar-style: Translucent

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&SESSION.'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Top Navigation Mega Menu # 46986644253953702466
  template-options: 
  - '#DEFAULT#'
  list-position: Top
  list: Navigation Menu # 46986483541938702397

navigation-bar: 
  implementation: List
  list: Navigation Bar # 46986677670123702487
  list-template: Navigation Bar # 46986640423418702464
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#APP_FILES#css/global#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: true
  add-"built-with-apex"-to-footer: true

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 8520923407811928
  identification: 
    name: APP_NAME

  value: 
    static-value: WMGT

application-settings: 
- # ====== Application Setting: FEEDBACK_ATTACHMENTS_YN ========
  id: 46986683643759702497
  identification: 
    name: FEEDBACK_ATTACHMENTS_YN

  value: 
    value: Y
    required: false

  advanced: 
    valid-values: Y, N
    on-upgrade-keep-value: true

  configuration: 
    build-option: 'Feature: Feedback' # 46986680133641702495

- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 46986683946025702497
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ACL_ONLY
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  configuration: 
    build-option: 'Feature: Access Control' # 46986679954839702495

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

